### ISSUE TITLE
Basic policy missing

### ISSUE THREAD

**Issue by JelenaKovacc** [ertis-research/opentwins#20]
How to manually import basic policy for creating type/twin? I installed the latest version of Opentwins with Helm.

Thanks!

**Comment by sergioinf** [comment]
The basic policy should appear when you click on create twin/type and the Policy.

![image](https://github.com/user-attachments/assets/ebb3fe26-f895-4e08-8ec1-9d2f8bb555b3)

**Comment by JelenaKovacc** [comment]
When I want to choose policy, I get the following:
![Screenshot_5-9-2024_133118_127 0 0 1](https://github.com/user-attachments/assets/908f8b8c-a9e6-4f64-96ac-7f8ff563ad9d)

Also, on localhost:30526/api/policies there is nothing:

![Screenshot_5-9-2024_13329_127 0 0 1](https://github.com/user-attachments/assets/9ae37bdb-4ac3-41c0-a417-36f78123affe)

Few days ago pods were in running state, now mosquitto and telegraf have errors:
![image](https://github.com/user-attachments/assets/dcb91144-ea6a-4823-ab82-1ed33f08cdbd)
![image](https://github.com/user-attachments/assets/6d9fe52a-f75c-4d89-be03-593cf1d8b05a)

What should I do? Thanks!

**Comment by JelenaKovacc** [comment]
I figured it out - after-install jobs couldn't do their job because I didn't run commands as administrator. After that, everything looks ok, thanks!
