### ISSUE TITLE
Error in Open twin installation 

### ISSUE THREAD

**Issue by charanhs123** [ertis-research/opentwins#5]
Hello Ertis Research group, i am trying to install Opentwins on my server to create a digital twin , but i am facing this error in installation 

iffroot4@iff-dt:~$ helm repo add eclipse-iot https://eclipse.org/packages/charts
helm repo update

kubectl create namespace $NS
kubectl apply -f pv-hono.yaml -n $NS
kubectl apply -f pv-mongodb.yaml -n $NS
kubectl apply -f pvc-mongodb.yaml -n $NS

helm install -n $NS --wait --timeout 15m dt eclipse-iot/cloud2edge --version=0.2.3 -f values-cloud2edge.yaml --dependency-update --debug
"eclipse-iot" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ertis" chart repository
...Successfully got an update from the "eclipse-iot" chart repository
Update Complete. ⎈Happy Helming!⎈
namespace/cloud2edge created
persistentvolume/dt-pv-device-registry unchanged
persistentvolume/dt-pv-mongodb unchanged
persistentvolumeclaim/dt-pvc-mongodb created
install.go:214: [debug] Original chart version: "0.2.3"
install.go:231: [debug] CHART PATH: /home/iffroot4/.cache/helm/repository/cloud2edge-0.2.3.tgz

client.go:142: [debug] creating 67 resource(s)
wait.go:48: [debug] beginning wait for 67 resources with timeout of 15m0s
ready.go:297: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. observedGeneration (0) does not match spec generation (1).
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: cloud2edge/ditto-mongodb. 0 out of 1 expected pods are ready
^CRelease dt has been cancelled.
Error: INSTALLATION FAILED: context canceled
helm.go:84: [debug] context canceled
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:154
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_amd64.s:1650

**Comment by juliarobles** [comment]
Hello!

It seems according to the logs that the mongodb that installs the cloud2edge package has some problem with your cluster. We recommend you to try the [Helm installation](https://ertis-research.github.io/opentwins/docs/installation/using-helm), as it is much less complex than the manual one and probably avoids many errors. In it instead of using the cloud2edge package we join the components ourselves (avoids a lot of errors). Remove any components you have manually installed before testing helm to avoid possible problems.

Try Helm and let us know :)

**Comment by charanhs123** [comment]
Hello ,
Itried installing like you mentioned but , I noticed something strange that after installing through Opentwins, I didn't get all the services also I tried the Cloud2edge and didn't get the service like "hono-dispatch-router-ext", which is actually required while connecting ditto and honor, I am attaching the screenshot below.
![Screenshot from 2024-05-08 12-46-04](https://github.com/ertis-research/opentwins/assets/51820986/8e993c36-68fe-45df-b6f8-f8227ef47f94)

**Comment by juliarobles** [comment]
You should better check the pods instead of the services, to know if they are Running and Ready or not. With the OpenTwins helm we no longer install Eclipse Hono by default because it is not recommended if we deal with large amounts of data (see our [architecture](https://ertis-research.github.io/opentwins/docs/overview/architecture)). However, if you want to install it you can add in the installation command `--set hono.enabled=true`. 

Also, I see you still have the cloud2edge package installed, I recommend you to uninstall it as it is no longer used in the platform and can give you port incompatibilities with the Helm installation.

Regards :)

**Comment by charanhs123** [comment]
Hello i did like you told but nothing has changed,
![Screenshot from 2024-05-08 13-59-57](https://github.com/ertis-research/opentwins/assets/51820986/028adb25-5862-4a57-8139-72b2f69e37e1)

**Comment by juliarobles** [comment]
Everything seems to install fine except mongodb, can you do `kubectl logs` and `kubectl describe pod` from the mongodb pod to see what might be going on?

**Comment by charanhs123** [comment]
Hello @juliarobles the problem was actually with the Processor of VM in Proxmox which was set to Qemu, now I changed into sandbox , the pods are working now.
Thank you

**Comment by charanhs123** [comment]
Also @juliarobles, when will the guide for 3D Visualisation using Unity be uploaded on the Website? Its much needed

**Comment by juliarobles** [comment]
I'm glad it worked for you in finally. We are going to give priority to make the guide for the Unity part, a lot of people are asking for it, but we don't have much time. We hope to have it as soon as possible. 

I'm going to close the issue :)
Regards,
Julia
