### ISSUE TITLE
Request for uploading Descriptions and steps in 3 sections

### ISSUE THREAD

**Issue by charanhs123** [ertis-research/opentwins#8]
Hello Ertis-research team,

I have been using Open Twins for my digital twin platform Thesis, and I request you guys upload steps and descriptions of the sections
1. Kafka and ML
2. 3D visualization using Unity 
3. Simulations

this could help me understand and develop our work in DTP's.

I appreciate any help you can provide.

**Comment by sergioinf** [comment]
Hello!
We are writing the documentation gradually and changing the priorities depending on what we see that is more urgent. We have seen that especially the guide for 3D visualization is being demanded by many users, so it will be one of the next to appear in the wiki if not the next one.
